default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123qwe!@#
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: bookshare_development

staging:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>

test:
  <<: *default
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  database: bookshare_test
  username: root
  password: 123qwe!@#

production:
  <<: *default
  database: bookshare_production
