default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123qwe!@#
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: bookshare_development

staging:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>

test:
  <<: *default
  database: bookshare_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
