default: &default
  encoding: utf8
  pool: 5


development:
  <<: *default
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  database: bookshare_development
  username: root
  password: 123qwe!@#

staging:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>

test:
  <<: *default
  adapter: mysql2
  socket: /var/run/mysqld/mysqld.sock
  database: bookshare_test
  username: root
  password: 123qwe!@#

production:
  <<: *default
  adapter: postgresql
  database: bookshare_production
  username: bookshare
  password: <%= ENV['BOOKSHARE_DATABASE_PASSWORD'] %>
